In [1]:
#NumPy

In [2]:
#NumericalPython

In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
#creating arrays

In [6]:
sample_array=np.array([1,2,3,4])

In [7]:
sample_array

array([1, 2, 3, 4])

In [10]:
#2D array (Matrix)

In [12]:
sample_array2=np.array([[1,2],[3,4]])

In [13]:
sample_array2

array([[1, 2],
       [3, 4]])

In [14]:
# 3D array (tensor)

In [23]:
sample_array3=np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

In [16]:
sample_array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#Dimension
# 0-D (Scalar)-Number
# 1-D (vector)-List
# 2-D (Matrix)-A table with rows and columns
# 3-D (Tensor)-A stack of tables

In [21]:
sample_array3=np.array([
    [[92,93],[93,94]],
    [[95,96],[97,98]]
])

In [22]:
sample_array3

array([[[92, 93],
        [93, 94]],

       [[95, 96],
        [97, 98]]])

In [24]:
#Array properties

In [27]:
sample_array2=np.array([[1,2,3],[4,5,6]])

In [28]:
sample_array2

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
#shape

In [30]:
sample_array2.shape

(2, 3)

In [31]:
sample_array2.ndim

2

In [33]:
sample_array2.size

6

In [34]:
sample_array2.dtype

dtype('int64')

In [44]:
sample_array=np.array([
    [[12,13],[13,14]],
    [[14,15],[15,16]]
])

In [49]:
#array properties

In [43]:
sample_array

array([1, 2, 3, 4])

In [45]:
sample_array.shape

(2, 2, 2)

In [46]:
sample_array.ndim

3

In [47]:
sample_array.size

8

In [48]:
sample_array.dtype

dtype('int64')

In [50]:
sample_array2=np.array([[0,0,0],[0,0,0]])

In [51]:
sample_array2

array([[0, 0, 0],
       [0, 0, 0]])

In [52]:
sample_array2=np.array([[1,1,1],[1,1,1]])

In [53]:
sample_array2

array([[1, 1, 1],
       [1, 1, 1]])

In [54]:
#Special arrays

In [55]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [58]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [74]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [75]:
a

array([1, 2, 3])

In [76]:
b

array([4, 5, 6])

In [77]:
#add

In [78]:
a+b

array([5, 7, 9])

In [79]:
a-b

array([-3, -3, -3])

In [80]:
a*b

array([ 4, 10, 18])

In [81]:
a/b

array([0.25, 0.4 , 0.5 ])

In [82]:
#Mathematical Function

In [86]:
sample_array = np.array([1,4,9])

In [87]:
sample_array

array([1, 4, 9])

In [89]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [90]:
#log

In [91]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [92]:
#Expo

In [93]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [94]:
#Statistical functions

In [97]:
sample_array1=np.array([1,2,3,4,5,6,7,8,9])

In [98]:
sample_array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#mean

In [101]:
np.mean(sample_array1)

np.float64(5.0)

In [104]:
#median

In [103]:
np.median(sample_array1)

np.float64(5.0)

In [105]:
#Standard deviation

In [106]:
np.std(sample_array1)

np.float64(2.581988897471611)

In [111]:
#min

In [107]:
np.min(sample_array1)

np.int64(1)

In [110]:
#max

In [108]:
np.max(sample_array1)

np.int64(9)

In [112]:
array=np.array([68,67,58,1003])

In [113]:
array

array([  68,   67,   58, 1003])

In [115]:
np.mean(array)

np.float64(299.0)

In [120]:
np.min(array)

np.int64(58)

In [117]:
np.max(array)

np.int64(1003)

In [118]:
np.std(array)

np.float64(406.47324635208156)

In [119]:
np.median(array)

np.float64(67.5)

In [10]:
import numpy as np

In [11]:
s2=np.array([[1,2],[3,4]])

In [12]:
s2

array([[1, 2],
       [3, 4]])

In [14]:
s2.flatten()

array([1, 2, 3, 4])

In [15]:
a=np.array([1,2,])
b=np.array([3,4])

In [16]:
a

array([1, 2])

In [17]:
b

array([3, 4])

In [19]:
#join

In [20]:
a+b

array([4, 6])

In [22]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [23]:
s1=np.array([1,2,3,4])

In [24]:
s1

array([1, 2, 3, 4])

In [30]:
np.array_split(s1,2)

[array([1, 2]), array([3, 4])]

In [31]:
#Random module

In [32]:
np.random.rand(3)

array([0.43103754, 0.24556928, 0.25344726])

In [33]:
np.random.rand(10)

array([0.49253138, 0.89151568, 0.44775148, 0.00713103, 0.62683166,
       0.37748418, 0.7187373 , 0.67634231, 0.41878721, 0.87236067])

In [34]:
np.random.randint(1,100,10)

array([15, 99,  2, 56, 18, 98, 47, 44, 75, 15], dtype=int32)

In [45]:
S2=np.array(([1,2],[3,4]))

In [46]:
S2

array([[1, 2],
       [3, 4]])

In [47]:
np.sum(S2,axis=0)

array([4, 6])

In [52]:
S3=np.array([1,np.nan,3])

In [53]:
S3

array([ 1., nan,  3.])

In [56]:
np.isnan(S3)

array([False,  True, False])

In [61]:
S4=np.array([[3,np.nan],[np.nan,6]])

In [64]:
np.isnan(S4)

array([[False,  True],
       [ True, False]])

In [65]:
arr=np.array([0,1,2,3,4,5])

In [66]:
arr

array([0, 1, 2, 3, 4, 5])

In [67]:
arr.reshape(2,3)

AttributeError: 'numpy.ndarray' object has no attribute 'reshaped'